#include "keyboard.h"
#include "framebuffer.h"
#include "io.h"
#include "pic.h"

//Description
//Lookup table that maps keyboard scan codes to ASCII characters.
//Purpose
//Provides a fast conversion from scan codes to printable characters.

/* US QWERTY, scan code set 1 (make codes). */
static const char scancode_ascii[128] =
{
    0,   27,  '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '=', '\b',
    '\t', 'q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p', '[', ']', '\n',
    0,   'a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';', '\'', '`',
    0,   '\\', 'z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.', '/', 0,
    '*', 0,   ' '
};

//Description
//Reads the latest scan code generated by the keyboard from I/O port 0x60.
//Purpose
//Retrieves the raw keyboard input before it is translated into an ASCII character.

unsigned char read_scan_code(void)
{
    return inb(KBD_DATA_PORT);
}

//Description
//Converts a keyboard scan code into its corresponding ASCII character using the lookup table.
//Purpose
//Translates hardware-specific key codes into readable characters.

char keyboard_scancode_to_ascii(unsigned char scan_code)
{
    if (scan_code & 0x80)
    {
        return 0;
    }

    if (scan_code >= sizeof(scancode_ascii))
    {
        return 0;
    }

    return scancode_ascii[scan_code];
}

//Description
//Enables keyboard interrupts by removing the keyboard IRQ mask in the PIC.
//Purpose
//Allows the CPU to start receiving keyboard interrupt requests.
void keyboard_init(void)
{
    pic_clear_mask(KBD_IRQ);
}

//Description
//Handles keyboard interrupts by reading the scan code, converting it to ASCII, and displaying the character on the screen.
//Purpose
//Processes key presses whenever the keyboard generates an interrupt.
void keyboard_interrupt(void)
{
    unsigned char scan_code;
    char c;

    scan_code = read_scan_code();

    if (scan_code == 0xE0)
    {
        (void) read_scan_code();
        return;
    }

    c = keyboard_scancode_to_ascii(scan_code);

    if (c != 0)
    {
        fb_write(&c, 1);
    }
}
